in:
  type: file
  path_prefix: test-data
  parser:
    type: csv
    columns:
      - { name: id, type: long }
      - { name: name, type: string }
      - { name: category, type: string }
      - { name: amount, type: double }
    skip_header_lines: 1

out:
  type: multi
  outputs:
    - type: stdout
    - type: file
      path_prefix: output/test-output-1
      file_ext: csv
      formatter:
        type: csv
    - type: file
      path_prefix: output/test-output-2
      file_ext: json
      formatter:
        type: jsonl
