name: Code Quality

on:
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run Checkstyle (if configured)
      run: ./gradlew checkstyleMain checkstyleTest
      continue-on-error: true

    - name: Run SpotBugs (if configured)
      run: ./gradlew spotbugsMain spotbugsTest
      continue-on-error: true

    - name: Generate Javadoc
      run: ./gradlew javadoc

    - name: Upload Javadoc
      uses: actions/upload-artifact@v4
      with:
        name: javadoc
        path: build/docs/javadoc/

    - name: Check dependencies for vulnerabilities
      run: ./gradlew dependencyCheckAnalyze
      continue-on-error: true

    - name: Upload dependency check results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: build/reports/
      continue-on-error: true
